name: Python package

on: [push, pull_request]

jobs:
  build:
    name: bitcoind ${{ matrix.bitcoind-version}}, python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        bitcoind-version: ["26.1"]
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint with flake8
        run: |
          sudo apt install python3-pip
          pip3 install flake8
          ./test/lint/lint-python.sh
      - name: Cache bitcoind
        uses: actions/cache@v3
        env:
          cache-name: bitcoind
          BITCOIND_VERSION: ${{ matrix.bitcoind-version }}
        with:
          path: ~/bitcoin/*/bin/bitcoin*
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.BITCOIND_VERSION }}-${{ hashFiles('test/install_bitcoind.sh') }}
      - name: Install bitcoind
        env:
          BITCOIND_VERSION: ${{ matrix.bitcoind-version }}
        run: ./test/install_bitcoind.sh
      - name: Install SatSale
        run: pip3 install -r requirements.txt
      - name: Run tests
        run: |
          pip3 install pytest
          ./test/run_tests.sh
